# Generated by Django 4.0 on 2025-04-30 15:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("age", models.PositiveIntegerField(verbose_name="Age")),
                (
                    "type",
                    models.CharField(
                        choices=[("dog", "Dog"), ("cat", "Cat")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Creation Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PetPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=pets.models.pet_photo_path, verbose_name="Photo"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Upload Date"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="pets.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet Photo",
                "verbose_name_plural": "Pet Photos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
